### ISSUE TITLE
How can we browse the eventstore records ?

### ISSUE THREAD

**Issue by manelephant** [qandidate-labs/broadway-demo#13]
Hello,

I am trying to make the demo work but i cannot browse event storage.

Would it be possible to have a little help on how to setup mysql for eventstorage ?

I fact i added mysql as doctrine/dbal but executing "broadway:event-store:schema:init" doesn't show any schema or tables.

Thank you so much

**Comment by wjzijderveld** [comment]
Hi @manelephant 

As you closed it, is it clear to you? 
I'm not 100% sure what you meant, of things didn't work or things are unclear.

If you want to know anything else, let me know!

**Comment by manelephant** [comment]
Hi !

Yes this step is ok for me now.

I have a question though : It seems that data are not added to elasticsearch when events are added. Do you have a small tip to check if datas are well added ?

For example i query : http://broadway.local:9200/_search?q=*:* but it return 0 results.

Thank you so much

**Comment by wjzijderveld** [comment]
It's the correct way (you can leave of the `q` though)
But the only read model created, is the triggered on checkout. So make sure to have a working basket, with products, and POST to /basket/<id>/checkout. 

See the README for all the endpoints.

**Comment by manelephant** [comment]
Thanx i got it !!!

Great job you made there - coming from geteventstore + scala it's really nice to try ES/CQRS with symfony.

**Comment by wjzijderveld** [comment]
Be aware that this demo is a bit out of date, so some of the code examples won't work with latest Broadway anymore. See the CHANGELOG for some of the breaking changes (mostly trivial stuff)

**Comment by wjzijderveld** [comment]
Oh, and have you seen this https://github.com/dbellettini/broadway-eventstore :smile:

**Comment by manelephant** [comment]
Ok thanx for the changelog info.

Wow thats great to have a GES connector !

For hacking purpose being able to store events in mysql is very valuable. From my own experience querying into GES was pretty tedious.
