### ISSUE TITLE
Rename the EventSourcingRepository::add() method to save()

### ISSUE THREAD

**Issue by GromNaN** [qandidate-labs/broadway-demo#16]
I couldn't figure out why this demo was not working until I find this change:
https://github.com/qandidate-labs/broadway/commit/9b07dfc4998d70b4c6d25dcacf114a60ea7f1450

The method `EventSourcingRepository::add()` should have been kept for BC and deprecated.

**Comment by wjzijderveld** [comment]
Thats why I started on this: https://github.com/qandidate-labs/broadway-demo/pull/14/files Just never got around to finish it. 

And we arent always going to keep BC while we are in 0.x.

**Comment by GromNaN** [comment]
Ok, thank you.
