### ISSUE TITLE
Event and Command 

### ISSUE THREAD

**Issue by harikt** [qandidate-labs/broadway-demo#4]
Hey,

It seems to me it would be nice to move the events to `Event` folder and command to `Command` folder ( https://github.com/qandidate-labs/broadway-demo/tree/master/src/BroadwayDemo/Basket ).

That way things will look neat.

Just a suggestion.

Thanks

**Comment by wjzijderveld** [comment]
We like to keep all stuff regarding an aggregate in the same directory. 
Although we usually suffix classes with `Event` or `Command` which makes identifying the files easier. 

But this demo is to demonstrate how Broadway can be used within an application. It's not meant as best practices guide. Therefore I don't think we should focus on directory structure.

**Comment by harikt** [comment]
I look demo's as the way people learn things.

**Comment by ruudk** [comment]
Well I agree. It think it would be better to make subfolders per aggregate.
